<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="0.117" timestamp="2025-10-11T22:04:36.422811" hostname="jinhyuk2box"><testcase classname="shopee_main_service" name="" time="0.000"><error message="collection failure">/usr/lib/python3/dist-packages/pluggy/_hooks.py:501: in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
/usr/lib/python3/dist-packages/pluggy/_manager.py:119: in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
/usr/lib/python3/dist-packages/_pytest/python.py:215: in pytest_collect_file
    module: Module = ihook.pytest_pycollect_makemodule(
/usr/lib/python3/dist-packages/_pytest/config/compat.py:66: in fixed_hook
    return hook(**kw)
/usr/lib/python3/dist-packages/pluggy/_hooks.py:501: in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
/usr/lib/python3/dist-packages/pluggy/_manager.py:119: in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
/opt/ros/jazzy/lib/python3.12/site-packages/launch_testing/pytest/hooks.py:193: in pytest_pycollect_makemodule
    entrypoint = find_launch_test_entrypoint(path)
/opt/ros/jazzy/lib/python3.12/site-packages/launch_testing/pytest/hooks.py:183: in find_launch_test_entrypoint
    module = import_path(path, root=None)
/usr/lib/python3/dist-packages/_pytest/pathlib.py:567: in import_path
    importlib.import_module(module_name)
/usr/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1387: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1360: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:1331: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:935: in _load_unlocked
    ???
&lt;frozen importlib._bootstrap_external&gt;:995: in exec_module
    ???
&lt;frozen importlib._bootstrap&gt;:488: in _call_with_frames_removed
    ???
shopee_main_service/__init__.py:4: in &lt;module&gt;
    from .config import MainServiceConfig
shopee_main_service/config.py:13: in &lt;module&gt;
    from pydantic_settings import BaseSettings, SettingsConfigDict
E   ModuleNotFoundError: No module named 'pydantic_settings'</error></testcase></testsuite></testsuites>